# ename=input("Enter your name: ")
# eaddress=input("Addres halum: ")
# esalary=input("Salary: ")
# phone=input("Phone halum: ")
# f=open("employee.txt","w")
# f.write(ename+"\n")
# f.write(eaddress+"\n")
# f.write(esalary+"\n")
# f.write(phone+"\n")
# f.close()

f=open("employee.txt","r")
print(f.read())
f.close()